# French wrong lang code
python app.py --input_text "Vous venez de commencer à apprendre le français ? Essayez nos Histoires quotidiennes, des articles de presse succincts et faciles à digérer conçus pour les étudiants débutants. Avec l'audio, les info-bulles de traduction et les notes éducatives sur chaque phrase, vous lirez et parlerez le français en un rien de temps, tout en restant à jour sur des sujets d'actualité et stimulants." \
              --language_code "some_code"

# French
python app.py --input_text "Vous venez de commencer à apprendre le français ? Essayez nos Histoires quotidiennes, des articles de presse succincts et faciles à digérer conçus pour les étudiants débutants. Avec l'audio, les info-bulles de traduction et les notes éducatives sur chaque phrase, vous lirez et parlerez le français en un rien de temps, tout en restant à jour sur des sujets d'actualité et stimulants." \
              --language_code "fr"

# Spanish
python app.py --input_text "Felipe Juan Pablo Alfonso de Todos los Santos de Borbón y Grecia; nacido el 30 de enero de 1968) es el Rey de España. Es hijo del ex rey Juan Carlos I y de la reina Sofía, y tiene dos hermanas mayores, la infanta Elena, duquesa de Lugo, y la infanta Cristina. En 2004, Felipe se casó con la periodista de noticias de televisión Letizia Ortiz con quien tiene dos hijas, Leonor (su presunta heredera) y Sofía. De acuerdo con la Constitución española, como monarca, es jefe del Estado y comandante en jefe de las Fuerzas Armadas españolas con el grado militar de Capitán General,[3][4] y desempeña también el papel de representación suprema de España en las relaciones internacionales.[3][4] Felipe ascendió al trono el 19 de junio de 2014 tras la abdicación de su padre.[5][6][7] Su reinado ha estado marcado por su disolución del Parlamento español en 2016 (para que se pudieran convocar nuevas elecciones), una fuerte condena al referéndum de independencia de Cataluña, la pandemia de COVID-19 y avances hacia una mayor transparencia en los asuntos reales." \
              --language_code "es"

# Afrikaans
python app.py --input_text "Felipe Juan Pablo Alfonso de Todos los Santos de Borbón y Grecia; gebore 30 Januarie 1968) is die koning van Spanje. Hy is die seun van voormalige koning Juan Carlos I en koningin Sofía, en het twee ouer susters, Infanta Elena, hertogin van Lugo, en Infanta Cristina. In 2004 trou Felipe met die TV-nuusjoernalis Letizia Ortiz met wie hy twee dogters het, Leonor (sy vermoedelike erfgenaam) en Sofía. In ooreenstemming met die Spaanse Grondwet is hy as monarg staatshoof en opperbevelhebber van die Spaanse Weermag met die militêre rang van Kaptein-generaal,[3][4] en speel ook die rol van die opperste verteenwoordiging van Spanje in internasionale betrekkinge.[3][4] Felipe het op 19 Junie 2014 die troon bestyg met die abdikasie van sy pa.[5][6][7] Sy bewind is gekenmerk deur sy ontbinding van die Spaanse parlement in 2016 (sodat nuwe verkiesings uitgeroep kan word), sterk veroordeling van die Kataloniese onafhanklikheidsreferendum, die COVID-19-pandemie, en skuif na groter deursigtigheid in koninklike sake." \
              --language_code "af"
 
# Swedish
python app.py --input_text "Felipe Juan Pablo Alfonso de Todos los Santos de Borbón y Grecia; född 30 januari 1968) är kung av Spanien. Han är son till före detta kung Juan Carlos I och drottning Sofia, och har två äldre systrar, Infanta Elena, hertiginnan av Lugo och Infanta Cristina. År 2004 gifte sig Felipe med TV-nyhetsjournalisten Letizia Ortiz som han har två döttrar med, Leonor (hans arvtagare) och Sofia. I enlighet med den spanska konstitutionen är han som monark statschef och överbefälhavare för de spanska väpnade styrkorna med militär rang som generalkapten[3][4] och spelar också rollen som den högsta representationen av Spanien i internationella förbindelser.[3][4] Felipe besteg tronen den 19 juni 2014 efter sin fars abdikation.[5][6][7] Hans regeringstid har präglats av hans upplösning av det spanska parlamentet 2016 (så att nya val kunde utlysas), ett starkt fördömande av den katalanska självständighetsfolkomröstningen, covid-19-pandemin och steg mot större öppenhet i kungliga angelägenheter." \
              --language_code "sv"

